defaults: &defaults
  gcx_url: 'https://wpdev.gcx.org'
  cas_url: 'https://casdev.gcx.org'

development:
  <<: *defaults

staging: &testing
  <<: *defaults

test: &testing
  <<: *defaults

production:
  <<: *defaults

